# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site title
title: "IMHO"

# Site logo
logo:

# A description of your site for social meta tag, search engines, and feed.xml
description: "My humble opinions and stuff"

# Tagline below the site title
tagline: "My humble opinions and stuff"

# The subpath of your site, e.g. /blog, for generating urls
baseurl:

sass:
  sass_dir: _sass

# The base hostname & protocol of your site for where absolute urls are needed
url: "http://hskang9.github.io"

# Site navigation - each item must have a title and a url.
navigation:
- text: Home
  url: /
- text: About
  url: /about/
- text: Style Guide
  url: /style-guide/
- text: Archives
  url: /tags/

# The shortname for your Disqus site to enable comments.
disqus: hskang9-github-io

# Author information - author info at the bottom of the post
author_name: "Hyungsuk Kang"
author_bio: "My name is Hyungsuk Kang. I’m a ML/DL enthusiast and student in Sungkyunkwan University. I talk about Data Science, Machine Learning, Artificial Intelligence, and Robotics"
author_url: "http://hskang9.github.io"
author_location: "Daejeon, SouthKorea"
author_image: hskang9.jpg

# Footer ad banner
banner_url: "https://justgoodthemes.com/"
banner_image: banner.jpg

# Footer newsletter widget - add your form action url for MailChimp signup form here
mailchimp_url: "//justgoodthemes.us3.list-manage.com/subscribe/post?u=78f1bab16028354caeb23aecd&amp;id=4a7330d117"

# Social links in the site footer
twitter_username: ""
facebook_username: "hskang960"
googleplus_username: "+username"
github_username: "hskang9"
codepen_username: "hskang9"
dribbble_username: "username"
medium_username: "@hyungsukkang"
instagram_username: "hyungsuk_k
"
pinterest_username: "username"
linkedin_username: "hyungsuk-kang-5217a7103"

# http://jekyllrb.com/docs/pagination/
paginate: 5
paginate_path: '/blog/page:num/'
gems: [jekyll-paginate]

permalink: pretty
markdown: kramdown
kramdown:
    auto_ids: false

google_analytics: UA-109751565-1
